---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - npm install -g bower
  - npm install -g ember-cli
  - npm install
  - bower install

script:
  - echo "test"
